<a href="https://colab.research.google.com/github/DevanshikaPiparsania/Basic-Fundamentals-Presentations/blob/main/Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Intoduction to Numpy!!

NumPy, short for Numerical Python, is a powerful open-source library in Python that provides support for large, multi-dimentional array and matrics, along with a collection of high level mathematical functions to operate on these arrays.

Now, you may be thinking, wait what about lists? Well lists are great but they take long time to process. Numpy arrays are 50 times faster than python lists and have a lots of functionality! This is because numpy arrays stores data in contiguous block of memory, allowing for faster access and manipulation.

Importing Numpy

In [29]:
import numpy as np

Creating an Array

Creating an array is very simple. All you have to do is convert a list to an array using np.array().

In [10]:
arr = np.array([1, 2, 3, 4, 5]) #add a list inside
print(arr)

[1 2 3 4 5]


You can also make n dimentional array by inputting n dimentional list

In [11]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("dimensions",arr2d.ndim)
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("dimensions",arr3d.ndim) #ndim prints out the number of dimensions


dimensions 2
dimensions 3


You can also create an array with a certain number of dimensions while creating the array itself.

In [12]:
arr5d = np.array([1, 2, 3, 4, 5], ndmin=5)

print("dimensions",arr5d.ndim)

dimensions 5


ACCESSING ARRAY ELEMENTS

Accessing elemets of an array is very similar to accessing the elements of list. You access the element by index like so ```arr_name[inx]```.

In [13]:
arr = np.array([1,2,3,4,5])

print(arr[0])

1


Accessing elements of a double dimenssional array is slightly different



In [14]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('4nd element on 2st row: ', arr[1, 3])

2nd element on 1st row:  2
4nd element on 2st row:  9


This same syntax can be applied for tripple dimensional, quadriple dimensional, etc,arrays.

Wait for python list we had something called negative indexing. I could save list_name[-1] and it would gave me the last value of the list. Does the same thing apply for numpy arrays? and the answer is yes.

In [15]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


SLICING ARRAYS

You may remember slicing from list. Well slicing with numpy arrays is very smilar. Here is an example below.

In [18]:
arr = np.array([1,2,3,4,5])

print(arr[1:3]) # Remembr it is nt inclusive of the

[2 3]


You can also leave the beginning or end parameter blank to indicate starting from the beginning of the array or end of the array (Same as for python list). Here are some examples  below:

In [19]:
print (arr[:4])
print (arr[3:])
print (arr[:])

[1 2 3 4]
[4 5]
[1 2 3 4 5]


You can also slice  with negative indices

In [20]:
print (arr[-3:-1])

[3 4]


You can add another parameter called a step when doing slicing (same for python list). The step parameters indicates if the slice is skip any number.

In [21]:
print (arr[:4:2]) #it moves by 2 indices from the 0th index uptill the 4th index

[1 3]


SO HOW O YOU SLICE THE 2D ARRAY?

In [22]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print (arr[1,1:4]) #choses the row you want to go to and slice that row

print (arr[:,1:4]) #To Slice all the row

[7 8 9]
[[2 3 4]
 [7 8 9]]


DATA TYPES

Sometimes when you are inputting the numpy array into a machine learning model the numpy array will have to be of a certain datatype. well you can define your own numpy arrays to have certain datatypes.

Here are all type of data structures used in numpy arrays:



1.   i -> integer
2.   b -> boolean
3.   u -> unsigned integers
4.   f -> float
5.   c -> complex float
6.   m -> timedelta
7.   M -> datetime
8.   O -> object
9.   S -> string
10.  U -> unicode string
11.  V -> fixed chunked of memory for other type (void)

To look at the data type of a numpy you can use arr.dtype





In [23]:
print (arr.dtype)

int64


to dedine an array with a certain type you can add it as a parameter

In [24]:
arr = np.array([1,2,3,4,5], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


Numpy Array are an Object

Something important to understand about Numpy Array are that they are object. This means that if you want to make a copy of an array you cannot just make a new variable and set it equal to the old array.



In [32]:
arr = np.array([1,2,3,4,5])
arr2 = arr
arr2[0] = 0
arr

array([0, 2, 3, 4, 5])

As you can see in the above example when we set arr2 = arr, arr was also changed. This is because setting them equal to each other make them point to the same reference causing the reference to arr to change rather that arr2 to change individually.
arr2-> reference of arr
arr2[0] = 0 , goes to the reference of arr that it points to and changes the element in the index of 0 to 0.


In [36]:
arr = np.array([1,2,3,4,5])
arr2 = arr.copy()
arr2[0] = 0
print(arr)
print(arr2)

[1 2 3 4 5]
[0 2 3 4 5]


Array Shape

To look at the shape of an array you can use this command

In [37]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr.shape)

arr2 = np.array([1,2,3,4,5])
print(arr2.shape)

(2, 5)
(5,)


In [38]:
arr = np.array([1,2,3,4,5], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4 5]]]]]
shape of array : (1, 1, 1, 1, 5)


You can reshape the array with this command

In [39]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3) #(ROWS, COLUMN)

newarr

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [40]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

newarr = arr.reshape(2,2,4)

newarr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

Notice how if you multiple the parameters in the reshape method (the dimensions)
you get the number of elements in the first array. If this is not true it will raise an error.  So what if you dont know the exact number to add for the last dimension? Well good for you! Numpy allows one unknown dimension. You can use -1 to indicate the dimension you want numpy to figureout itself. Here is an example

In [44]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
newarr = arr.reshape(2,2,-1)
newarr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

To flatten an array or to convert a multidimensional array into 1 dimension array you can do this

In [45]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

newarr = arr.reshape(-1)

newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Some other things you might want to know

1.  Iterating through a numpy array is the same as the list
2.  To concatinate array you can do this



In [ ]:
np.concatinate((arr1,arr2))

In [46]:
#Concatinate along rows
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2 = np.array([[11,12,13,14,15],[16,17,18,19,20]])

newarr = np.concatenate((arr1,arr2), axis=1)
newarr


array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [47]:
#Stacking is done along a new axis (default axes is 0)
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

newarr = np.stack((arr1,arr2), axis=1)
newarr

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])